Repository LoveMyDaughter/TA_EasyRest, pull requests merged in 2022-09, with the labels that each got.

#103 Move out DB credentials to the json
  TAF_EasyRest/TestFramework/Tools/DB/DBConnectionWrapper.cs
  TAF_EasyRest/TestFramework/binUrls.json
Labels: Ant

#104 Remote easyrest creds
  TAF_EasyRest/TestFramework/binUrls.json
Labels: Ant

#106 Test restore restaurant
  TAF_EasyRest/TestFramework/PageComponents/Moderator/ArchivedRestaurantsPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Moderator/ModeratorPanelRestaurantsPage.cs
  TAF_EasyRest/TestFramework/Test/BaseTest.cs
  TAF_EasyRest/TestFramework/Test/ModeratorTests.cs
Labels: Ant

#107 Submit Order Test
  TAF_EasyRest/TestFramework/PageComponents/Client/RestaurantMenuComponents/CartPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Client/RestaurantMenuComponents/OrderConfirmationPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Client/RestaurantMenuPage.cs
  TAF_EasyRest/TestFramework/Pages/Unauthorized/RestaurantsListPage.cs
  TAF_EasyRest/TestFramework/Test/ClientTests.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBCleanup.cs
Labels: Sofi

#102 Add new restaurant test
  TAF_EasyRest/TestFramework/PageComponents/Client/NewRestaurantPageComponet.cs
  TAF_EasyRest/TestFramework/Pages/Client/NewRestaurantPage.cs
  TAF_EasyRest/TestFramework/Test/ClientTests.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBCleanup.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBSelections.cs
  TAF_EasyRest/TestFramework/binUrls.json
Labels: Sofi

#109 Add waiter test
  TAF_EasyRest/TestFramework/PageComponents/Owner/CreateNewAdministratorPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/CreateNewWaiterPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/ManageRestaurantPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/OwnerPanelPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/RestaurantItemPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/WaiterItemPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Owner/ManageAdministratorPage.cs
  TAF_EasyRest/TestFramework/Pages/Owner/ManageWaitersPage.cs
  TAF_EasyRest/TestFramework/Test/OwnerTests.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBAddition.cs
  TAF_EasyRest/TestFramework/binRolesCredentials.json
Labels: Tania

#108 Test change moderator status
  TAF_EasyRest/TestFramework/Pages/Admin/AdminPanelModeratorsPage.cs
  TAF_EasyRest/TestFramework/Test/AdminTests.cs
  TAF_EasyRest/TestFramework/Test/BaseTest.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBAddition.cs
Labels: Ant

#116 Update Nuget package ChromeDriver
  TAF_EasyRest/TestFramework/TestFramework.csproj
Labels: Ant

#111 Reorder test
  TAF_EasyRest/TestFramework/PageComponents/Client/HistoryOrderDetailsPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Client/OrderPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Client/RestaurantMenuComponents/OrderConfirmationPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Client/OrderHistoryPage.cs
  TAF_EasyRest/TestFramework/Test/ClientTests.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBCleanup.cs
  TAF_EasyRest/TestFramework/binUrls.json
Labels: Sofi

#121 Remove administrator test
  TAF_EasyRest/TestFramework/PageComponents/Owner/AdministratorItemPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/CreateNewWaiterPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/ManageRestaurantPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/WaiterItemPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Owner/ManageAdministratorPage.cs
  TAF_EasyRest/TestFramework/Pages/Owner/ManageWaitersPage.cs
  TAF_EasyRest/TestFramework/Test/BaseTest.cs
  TAF_EasyRest/TestFramework/Test/OwnerTests.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBAddition.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBConnectionWrapper.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBSelections.cs
Labels: Tania

#110 Administrator tests refactoring
  TAF_EasyRest/TestFramework/PageComponents/Administrator/AcceptedCardPageComponent.cs
  TAF_EasyRest/TestFramework/Test/AdministaratorTests.cs
Labels: Andriy

#119 Refactoring test change user status
  TAF_EasyRest/TestFramework/Test/BaseTest.cs
  TAF_EasyRest/TestFramework/Test/ModeratorTests.cs
Labels: Ant

#125 delete waiter
  TAF_EasyRest/TestFramework/PageComponents/Client/HistoryOrderDetailsPageComponent.cs
Labels: Sofi

#126 Add one more step to click Restaurants on the left-side menu
  TAF_EasyRest/TestFramework/Test/ModeratorTests.cs
Labels: Ant
