Repository LoveMyDaughter/TA_EasyRest, pull requests merged in 2022-08, with the labels that each got.

#66 Waiter panel page
  TAF_EasyRest/TestFramework/PageComponents/Administrator/AcceptedCardPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Administrator/AcceptedListPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Administrator/WaitingForConfirmCardPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Administrator/WaitingForConfirmListPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/AdministratorPanelComponents/AcceptedCardPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/AdministratorPanelComponents/WaitingForConfirmCardPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Waiter/AssignedWaiterCardPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Waiter/AssignedWaiterListPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Waiter/InProgressCardPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Waiter/InProgressListPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/AdministratorPanelPage.cs
  TAF_EasyRest/TestFramework/Pages/WaiterPanelPage.cs
Labels: Andriy

#67 Refactoring antonio
  TAF_EasyRest/TestFramework/PageComponents/Moderator/ArchivedRestaurantsPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Moderator/UnapprovedRestaurantsPageComponent .cs
  TAF_EasyRest/TestFramework/PageComponents/UnapprovedRestaurantPageComponent .cs
  TAF_EasyRest/TestFramework/Pages/Moderator/ModeratorPanelRestaurantsPage.cs
  TAF_EasyRest/TestFramework/TestFramework.csproj
  TAF_EasyRest/TestFramework/page_links.xlsx
Labels: Ant

#70 Create menu
  TAF_EasyRest/TestFramework/PageComponents/Owner/CreateMenuPageComponents/CreateListMenuEndPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/CreateMenuPageComponents/CreateListMenuPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Owner/CreateMenuPage.cs
Labels: Tania

#65 Add order confirmation page
  TAF_EasyRest/TestFramework/PageComponents/Client/RestaurantMenuComponents/CartPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Client/RestaurantMenuComponents/OrderConfirmationPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Client/RestaurantMenuComponents/OrderConfirmationWindowPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Client/RestaurantMenuComponents/OrderSummaryDetailsPageComponent.cs
Labels: Sofi

#69 Moderator panel owners page
  TAF_EasyRest/TestFramework/PageComponents/Moderator/UnapprovedRestaurantsPageComponent .cs
  TAF_EasyRest/TestFramework/Pages/Moderator/ModeratorPanelOwnersPage.cs
Labels: Ant

#71 Create manage menu page
  TAF_EasyRest/TestFramework/PageComponents/Client/NewRestaurantPageComponet.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/ChangeItemMenuPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/ManageMenuPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/ManageRestaurantPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Owner/CreateMenuPage.cs
  TAF_EasyRest/TestFramework/Pages/Owner/ManageAdministratorPage.cs
  TAF_EasyRest/TestFramework/Pages/Owner/ManageWaitersPage.cs
  TAF_EasyRest/TestFramework/Pages/Owner/MenuItemsPage.cs
Labels: Sofi

#72 Restaurant menu page refactoring
  TAF_EasyRest/TestFramework/PageComponents/Client/RestaurantMenuComponents/CartPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Client/RestaurantMenuComponents/MenuItemDetailsPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Client/RestaurantMenuComponents/MenuItemSummaryPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Client/RestaurantMenuPage.cs
Labels: Andriy

#73 Moderator panel page component
  TAF_EasyRest/TestFramework/PageComponents/Moderator/ModeratorPanelPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Moderator/ModeratorPanelOwnersPage.cs
  TAF_EasyRest/TestFramework/Pages/Moderator/ModeratorPanelUsersPage.cs
Labels: Ant

#76 Db integration
  TAF_EasyRest/TestFramework/Test/UnitTest1.cs
  TAF_EasyRest/TestFramework/TestFramework.csproj
  TAF_EasyRest/TestFramework/Tools/DBCleanup.cs
  TAF_EasyRest/TestFramework/Tools/DBConnectionWrapper.cs
Labels: Ant

#75 Add component for edit restaurant pge
  TAF_EasyRest/TestFramework/Pages/Owner/ManageWaitersPage.cs
  TAF_EasyRest/TestFramework/Pages/Owner/OwnerEditRestaurantPage.cs
Labels: Tania

#74 Add list of waiters
  TAF_EasyRest/TestFramework/PageComponents/Owner/OwnerEditRestaurantPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Owner/ManageWaitersPage.cs
Labels: Tania

#81 Remove waiter test
  TAF_EasyRest/TestFramework/PageComponents/Owner/ManageRestaurantPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/OwnerPanelPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/RestaurantItemPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/WaiterItemPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Owner/ManageWaitersPage.cs
  TAF_EasyRest/TestFramework/Pages/Owner/OwnerPanelRestaurantsPage.cs
  TAF_EasyRest/TestFramework/Test/OwnerTests.cs
Labels: Tania

#83 Fixed issue with cyrillic 'C'.
  TAF_EasyRest/TestFramework/Pages/Client/CurrentOrdersPage.cs
  TAF_EasyRest/TestFramework/Test/ClientTests.cs
Labels: Tania

#85 add changes
  TAF_EasyRest/TestFramework/PageComponents/Client/RestaurantMenuComponents/OrderConfirmationPageComponent.cs
Labels: Sofi

#88 Clean DBConnectionWrapper class
  TAF_EasyRest/TestFramework/Tools/DBConnectionWrapper.cs
Labels: Ant

#82 Implement waiters
  TAF_EasyRest/TestFramework/PageComponents/Administrator/WaitingForConfirmCardPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Administrator/WaitingForConfirmListPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/NavigationMenuComponents/UserMenuDropDownListPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/NavigationMenuComponents/UserMenuHeaderButtonPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/AdministratorPanelPage.cs
  TAF_EasyRest/TestFramework/Pages/BasePage.cs
  TAF_EasyRest/TestFramework/Test/ClientTests.cs
  TAF_EasyRest/TestFramework/TestFramework.csproj
  TAF_EasyRest/TestFramework/Tools/IWebDriverExtentions.cs
  TAF_EasyRest/TestFramework/Tools/IWebElementExtentions.cs
  TAF_EasyRest/TestFramework/Usings.cs
Labels: Andriy

#87 Base test
  TAF_EasyRest/TestFramework/Test/BaseTest.cs
  TAF_EasyRest/TestFramework/Test/UnitTest1.cs
  TAF_EasyRest/TestFramework/Tools/DBCleanup.cs
Labels: Ant

#89 Fix warnings
  TAF_EasyRest/TestFramework/Pages/Owner/MenuItemsPage.cs
  TAF_EasyRest/TestFramework/Test/OwnerTests.cs
Labels: Tania

#90 Test moderator change user status
  TAF_EasyRest/TestFramework/Pages/Moderator/ModeratorPanelUsersPage.cs
  TAF_EasyRest/TestFramework/Test/BaseTest.cs
  TAF_EasyRest/TestFramework/Test/ModeratorTests.cs
  TAF_EasyRest/TestFramework/Tools/IWebDriverExtentions.cs
Labels: Ant

#92 add serialization & deserialization
  TAF_EasyRest/TestFramework/Tools/GetData/GetRoleCredentials.cs
  TAF_EasyRest/TestFramework/Tools/GetData/GetUrls.cs
  TAF_EasyRest/TestFramework/Tools/GetData/RoleCredentials.cs
  TAF_EasyRest/TestFramework/Tools/GetData/Urls.cs
  TAF_EasyRest/TestFramework/binRolesCredentials.json
  TAF_EasyRest/TestFramework/binUrls.json
  TAF_EasyRest/TestFrameworkUrls.json
Labels: Sofi

#94 Add administrator test
  TAF_EasyRest/TestFramework/PageComponents/Owner/AdministratorItemPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/CreateNewAdministratorPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Owner/ManageRestaurantPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/Owner/ManageAdministratorPage.cs
  TAF_EasyRest/TestFramework/Pages/Owner/ManageWaitersPage.cs
  TAF_EasyRest/TestFramework/Test/OwnerTests.cs
  TAF_EasyRest/TestFramework/Tools/DBCleanup.cs
  TAF_EasyRest/TestFramework/Tools/WebDriverExtensions.cs
Labels: Tania

#95 Decline order test
  TAF_EasyRest/TestFramework/PageComponents/Client/WaitingForConfirmOrderDetailsPageComponent.cs
  TAF_EasyRest/TestFramework/PageComponents/Client/WaitingForConfirmOrderPageComponent.cs
  TAF_EasyRest/TestFramework/Pages/BasePage.cs
  TAF_EasyRest/TestFramework/Pages/Client/CurrentOrdersPage.cs
  TAF_EasyRest/TestFramework/Test/ClientTests.cs
  TAF_EasyRest/TestFramework/Tools/DBCleanup.cs
Labels: Sofi

#98 add base url to json
  TAF_EasyRest/TestFramework/Pages/BasePage.cs
  TAF_EasyRest/TestFramework/binUrls.json
Labels: Sofi

#91 Test moderator change owner status
  TAF_EasyRest/TestFramework/Pages/Moderator/ModeratorPanelOwnersPage.cs
  TAF_EasyRest/TestFramework/Test/ModeratorTests.cs
Labels: Ant

#96 Test moderator approve restaurant
  TAF_EasyRest/TestFramework/PageComponents/Moderator/UnapprovedRestaurantsPageComponent.cs
  TAF_EasyRest/TestFramework/Test/BaseTest.cs
  TAF_EasyRest/TestFramework/Test/ModeratorTests.cs
  TAF_EasyRest/TestFramework/Tools/DBAddition.cs
  TAF_EasyRest/TestFramework/Tools/DBCleanup.cs
Labels: Ant

#99 Update .gitignore
  .gitignore
Labels: Ant

#100 Delete RPortal.json
  TAF_EasyRest/TestFramework/ReportPortal.config.json
Labels: Ant

#101 Create a method for using DB query result
  TAF_EasyRest/TestFramework/Test/AdministaratorTests.cs
  TAF_EasyRest/TestFramework/Test/BaseTest.cs
  TAF_EasyRest/TestFramework/Test/ClientTests.cs
  TAF_EasyRest/TestFramework/Test/OwnerTests.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBAddition.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBCleanup.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBConnectionWrapper.cs
  TAF_EasyRest/TestFramework/Tools/DB/DBSelections.cs
Labels: Ant
